version: '3.9'
services:
  mmdeploy:
    image: mmdeploy:main
    container_name: mmdeploy
    privileged: true
    volumes:
      - ${ADMLOPS_PATH}/mmdeploy_extension:/root/workspace/mmdeploy_extension:rw
      - ${ADMLOPS_PATH}/mmdetection_extension:/root/workspace/mmdetection_extension:rw
      - ${ADMLOPS_PATH}/mmdetection3d_extension:/root/workspace/mmdetection3d_extension:rw
      - ${ADMLOPS_REP_PATH}/checkpoints:/root/workspace/checkpoints:rw
      - ${ADMLOPS_REP_PATH}/data:/root/workspace/data:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    # add environment variables to the container
    environment:
      - ADMLOPS_PATH=/root/workspace
      # for x11 display
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

    # specify used network
    networks:
      - admlops

    stdin_open: true
    tty: true
    ports:
      - "8080:8081"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

# use alread existing network
networks:
  admlops:
    external: true
